export { default as ArrowBigUp } from './ArrowBigUp.svelte';
export { default as ArrowLeft1 } from './ArrowLeft1.svelte';
export { default as AtSign } from './AtSign.svelte';
export { default as BadgeCheck } from './BadgeCheck.svelte';
export { default as Bell1 } from './Bell1.svelte';
export { default as AcademicCap1 } from './AcademicCap1.svelte';
export { default as Wrapper } from './Wrapper.svelte';
export { default as ArrowDownLeft1 } from './ArrowDownLeft1.svelte';
export { default as ArrowDownLeft2 } from './ArrowDownLeft2.svelte';
export { default as ArrowDownOnSquare1 } from './ArrowDownOnSquare1.svelte';
export { default as Animate } from './Animate.svelte';
export { default as ArchiveBox1 } from './ArchiveBox1.svelte';
// export * from './icons';
